[package]
name = "oxiuse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "oxiuselib"
path = "src/lib.rs"

[dependencies]
oxigraph = {path = "../oxigraph/lib"}
stopwatch = "0.0.7"